version: "3.8"

services:

  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - PASSWORD=${PASSWORD}
      - CUSTOM_RESULTS=false
      - DB_TYPE=sqlite
    restart: unless-stopped
    networks:
      traefik_proxy:
    labels:
      - traefik.enable=true
      - traefik.http.routers.librespeed.rule=Host(`librespeed.local`)
      - traefik.http.routers.librespeed.entrypoints=websecure
      - traefik.http.services.librespeed.loadbalancer.server.port=80
      - traefik.http.routers.librespeed.tls=true
