version: "3.8"

services:
  unbound:
    image: 'klutchell/unbound'
    restart: unless-stopped
    hostname: 'unbound'
    ports:
      - 5053:5053/udp
    networks:
      vpn:
        ipv4_address: 10.13.13.10

  pihole:
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    environment:
      TZ: Asia/Seoul
      WEBPASSWORD: ${PASSWORD}
      PIHOLE_DNS_: 10.13.13.10#5053;10.13.13.10#5053
      VIRTUAL_HOST: pihole.${DOMAIN}
    volumes:
      - ./.pihole/pihole/:/etc/pihole/
      - ./.pihole/dnsmasq.d:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: 10.13.13.20
      traefik_proxy:
    labels:
      - traefik.enable=true
      - traefik.http.routers.202207__pihole.entrypoints=websecure
      - traefik.http.routers.202207__pihole.rule=Host(`pihole.${DOMAIN}`)
      - traefik.http.routers.202207__pihole.tls.certresolver=leresolver
      - traefik.http.services.202207__pihole.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true

  wgeasy:
    image: weejewel/wg-easy:latest
    networks:
      traefik_proxy:
        #vpn:
        #ipv4_address: 10.13.13.30
    environment:
      PASSWORD: ${WGEASY_PASSWORD}
      WG_HOST: hyeon.pro
      WG_DEFAULT_ADDRESS: 10.8.0.x
      WG_DEFAULT_DNS: 1.1.1.1
      WG_ALLOWED_IPS: 0.0.0.0/0,::/0
        #WG_DEFAULT_DNS: 10.13.13.20
      # WG_DEFAULT_ADDRESS: 10.13.13.x
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.202207__wgeasy.entrypoints=websecure
      - traefik.http.routers.202207__wgeasy.rule=Host(`vpn.${DOMAIN}`)
      - traefik.http.routers.202207__wgeasy.tls.certresolver=leresolver
      - traefik.http.services.202207__wgeasy.loadbalancer.server.port=51821
      - com.centurylinklabs.watchtower.enable=true

# ########################### NETWORKS
networks:
  traefik_proxy:
    external: true
  vpn:
    ipam:
      config:
        - subnet: 10.13.13.0/24
