version: "3.8"

services:
  pihole:
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
    dns:
      - 127.0.0.1
      - 9.9.9.9
    environment:
      TZ: Asia/Seoul
      WEBPASSWORD: ${PASSWORD}
      PIHOLE_DNS_: 9.9.9.9;149.112.112.112;1.1.1.1
      ServerIP: 192.168.1.4
      VIRTUAL_HOST: pihole.${DOMAIN}
      DNSMASQ_LISTENING: all
      DHCP_ACTIVE: 'true'
      DHCP_START: 192.168.1.100
      DHCP_END: 192.168.1.199
      DHCP_ROUTER: 192.168.1.1
      DHCP_LEASETIME: 6
    volumes:
      - ./.pihole/pihole/:/etc/pihole/
      - ./.pihole/dnsmasq.d:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: '10.8.1.2'
      traefik_proxy:
    labels:
      - traefik.enable=true
      - traefik.http.routers.202207__pihole.entrypoints=websecure
      - traefik.http.routers.202207__pihole.rule=Host(`pihole.${DOMAIN}`)
      - traefik.http.routers.202207__pihole.tls.certresolver=leresolver
      - traefik.http.services.202207__pihole.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - dhcphelper

  dhcphelper:
    image: noamokman/dhcp-helper:latest
    container_name: dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 10.8.1.2
    cap_add:
      - NET_ADMIN

  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - PASSWORD=${PASSWORD}
      - CUSTOM_RESULTS=false
      - DB_TYPE=sqlite
    restart: unless-stopped
    networks:
      traefik_proxy:
    labels:
      - traefik.enable=true
      - traefik.http.routers.librespeed.rule=Host(`librespeed.local`)
      - traefik.http.routers.librespeed.entrypoints=websecure
      - traefik.http.services.librespeed.loadbalancer.server.port=80
      - traefik.http.routers.librespeed.tls=true

# ########################### NETWORKS
networks:
  traefik_proxy:
    external: true
  backend:
    ipam:
      config:
        - subnet: 10.8.0.0/24
